default_profile: claude
tools:
  enabled: true
profiles:
  - name: claude
    protocol: anthropic-messages
    model: claude-model-name
    base_url: https://api.anthropic.com
    api_key: ${ANTHROPIC_API_KEY}
    thinking: false
    max_tokens: 4096
  - name: openai-chat
    protocol: openai-chat-completions
    model: openai-model-name
    base_url: https://api.openai.com/v1
    api_key: ${OPENAI_API_KEY}
    thinking: false
    max_tokens: 4096
    chat_system_mode: multiple

  - name: openai-responses
    protocol: openai-responses
    model: openai-model-name
    base_url: https://api.openai.com/v1
    api_key: ${OPENAI_API_KEY}
    thinking: false
    max_tokens: 4096
