// Generated by .codex/skills/wiki-sync/scripts/sync_wiki.py
import { defineConfig } from "vitepress";

const activeItems = [
  { text: "add-ci-quality-gates", link: "/changes/active/add-ci-quality-gates/" },
];

const archivedItems = [
  { text: "improve-terminal-chat-experience", link: "/changes/archive/2026-08-12-improve-terminal-chat-experience/" },
  { text: "add-multi-protocol-llm-tui-chat", link: "/changes/archive/2026-08-11-add-multi-protocol-llm-tui-chat/" },
  { text: "scaffold-project-skeleton", link: "/changes/archive/2026-08-10-scaffold-project-skeleton/" },
];

export default defineConfig({
  lang: "zh-CN",
  title: "Weave WIKI",
  description: "Weave 项目文档与 OpenSpec 变更记录",
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "首页", link: "/" },
      { text: "变更 WIKI", link: "/changes/" }
    ],
    sidebar: {
      "/changes/": [
        { text: "总览", items: [{ text: "变更索引", link: "/changes/" }] },
        { text: "进行中", collapsed: false, items: activeItems },
        { text: "已归档", collapsed: true, items: archivedItems }
      ]
    },
    search: { provider: "local" },
    outline: { level: [2, 3], label: "本页目录" },
    docFooter: { prev: "上一页", next: "下一页" },
    sidebarMenuLabel: "目录",
    returnToTopLabel: "返回顶部"
  }
});
